### ISSUE TITLE
It always ask for sudo

### ISSUE THREAD

**Issue by cperezabo** [Keithbsmiley/zap#5]
Hi, I tried to uninstall `/Applications/Twitter.app` running `sudo zap -y Twitter.app` and it keeps saying it can't remove Twitter.app, "try it again with sudo".

¿Any idea?

**Comment by keith** [comment]
Are you able to `sudo rm -rf /Applications/Twitter.app`? Seems like that is the equivalent of what I'm checking https://github.com/keith/zap/blob/db834cd9e1da54a87bec3bb90b8d8afa9378faae/zap

**Comment by cperezabo** [comment]
Yes, I am. But when I do `sudo zap -y Twitter.app` I get the "Try running this again with 'sudo'" message.

**Comment by keith** [comment]
Can you run `ls -l /Applications/Twitter.app` and paste the output here? Seems like the detection needs to be smarter

**Comment by cperezabo** [comment]
Hi, yes 

```
❯ ls -l /Applications/Twitter.app
total 0
drwxr-xr-x  10 root  wheel  320 Nov 27 18:19 Contents/
```

**Comment by keith** [comment]
can you test with this change? https://github.com/keith/zap/pull/6
